name: 'bsi-panti-service'

services:
  mysql:
    image: mysql:8.4
    restart: always
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kb23ufg294vbojnsl
      MYSQL_DATABASE: example
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=kb23ufg294vbojnsl
      - PMA_ARBITRARY=1
